# Generated by Django 3.2.3 on 2021-05-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitees',
            old_name='user',
            new_name='invitee',
        ),
        migrations.RemoveField(
            model_name='items_for_invitees',
            name='user',
        ),
        migrations.AddField(
            model_name='items_for_invitees',
            name='invitee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eventlist.invitees'),
            preserve_default=False,
        ),
    ]
