# Generated by Django 3.2.3 on 2021-05-19 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventlist', '0002_auto_20210519_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventlist',
            new_name='Event',
        ),
    ]
