# Generated by Django 3.2.3 on 2021-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlist', '0004_alter_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitees',
            options={'verbose_name': 'Invitee', 'verbose_name_plural': 'Invitees'},
        ),
        migrations.AlterModelOptions(
            name='items_for_invitees',
            options={'verbose_name': 'Item_for_invitee', 'verbose_name_plural': 'Items_for_invitees'},
        ),
        migrations.AlterModelOptions(
            name='items_to_bring',
            options={'verbose_name': 'Item_to_bring', 'verbose_name_plural': 'Items_to_bring'},
        ),
        migrations.AddField(
            model_name='items_to_bring',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
