# Generated by Django 3.2.3 on 2021-05-26 17:14

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Your phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='profile',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
